### ISSUE TITLE
Implement streaming APIs

### ISSUE THREAD

**Issue by alanshaw** [tableflip/ipfs-postmsg-proxy#2]
Currently all streaming APIs "fake it" and buffer data into memory. We need something like [pull-postmsg](https://www.npmjs.com/package/pull-postmsg) to do this

**Comment by RangerMauve** [comment]
I'm pretty sure [fetch uses streams](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) which support backpressure. You'd need to convert the web `ReadableStream` to a `pull-stream`
