### ISSUE TITLE
Passing a pull-stream to ipfs.add is interpreted as a callback

### ISSUE THREAD

**Issue by olizilla** [tableflip/ipfs-postmsg-proxy#25]
If you pass a pull-stream to [`ipfs.add`](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#javascript---ipfsfilesadddata-options-callback) like:

```js
const pullStream = fileReader(file)
const ipfsRef = await ipfs.files.add(pullStream)
```

It's interpreted as a callback fn and callbackify is invoked, which causes an error in `callbackifyVariadic`

```
Type error: cb is not a function
```

Passing it as part of an array of entires avoids that issue, but then hits a known issue later on

```js
const pullStream = fileReader(file)
const ipfsRef = await ipfs.files.add([{content: pullStream}])
```

```
Error: content.once is not a function
```

**Comment by lidel** [comment]
Hm.. is this why `interface-ipfs-core` spec defines a separate [`ipfs.files.addPullStream`](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#addpullstream)?

**Comment by olizilla** [comment]
@lidel I agree, it is a little odd, but i think the api is meaningfully different from files.add...

- `ipfs.files.add(pullStream)` should let you hand a pull-stream to ipfs add and get a ipfsFileRef object back
- `ipfs.files.addPullStream()` returns a _through_ pull stream, that should let you add things to ipfs as step in a larger pull stream chain. 

Neither seems to work as expected currently.

**Comment by alanshaw** [comment]
Fixed here in: https://github.com/tableflip/ipfs-postmsg-proxy/commit/9884f7cd295b11aef7d7e8662ea4ee2f53d0cbec and https://github.com/tableflip/ipfs-postmsg-proxy/commit/ca487313d78b8a6d911adf06c1176c5c05d79583

`js-ipfs-api` issue https://github.com/ipfs/js-ipfs-api/issues/745 and PR https://github.com/ipfs/js-ipfs-api/pull/746

`js-ipfs` issue https://github.com/ipfs/js-ipfs/issues/1317 and PR TBC
